version: '3'

services:
  db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  db-admin:
    image: mongo-express
    links:
      - db:mongo
    ports:
      - 8081:8081
  telegram-bot:
    image: node
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - PATH=$PATH:node_modules/.bin
    command: gulp telegram-bot
