version: '2'

services:
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  db-admin:
    image: mongo-express
    links:
      - mongodb:mongo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=tywong
      - ME_CONFIG_BASICAUTH_PASSWORD=sosad369
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME}
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
  server:
    image: node
    volumes:
      - ./:/app
    working_dir: /app
    links:
      - mongodb
    environment:
      - PORT=3000
      - PATH=$PATH:node_modules/.bin
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DBNAME=kmb
    ports:
      - 3000:3000
    command: gulp server
  telegram-bot:
    image: node
    volumes:
      - ./:/app
    working_dir: /app
    links:
      - mongodb
    environment:
      - PATH=$PATH:node_modules/.bin
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DBNAME=kmb
    command: gulp telegram-bot
